- platform: template
  sensors:
    alexa_ha_fireplace:
      friendly_name: "Alexa HA - Fireplace Lamp"
      device_class: garage_door
      value_template: "{{ is_state('input_boolean.home_assistant_fireplace', 'on') }}"
