# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret
  # "Project ID" in the Device Access Console (not Cloud Project ID!)
  project_id: !secret nest_project_id
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /local/community/custom-brand-icons/custom-brand-icons.js
switch: !include switches.yaml
climate: !include climates.yaml
lock: !include locks.yaml
sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml
var: !include var.yaml
cloud:
  alexa:
    filter:
      include_domains:
        - switch
        - light
        - media_player
        - input_boolean
        - binary_sensor
homeassistant:
  allowlist_external_dirs:
    - /media
    - /config/nest/event_media
    - /config/www
