# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene default: !include scenes.yaml
scene saved: !include scenes/snapshot.yaml
wake_on_lan:
nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret
  # "Project ID" in the Device Access Console (not Cloud Project ID!)
  project_id: !secret nest_project_id
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /local/community/custom-brand-icons/custom-brand-icons.js
climate: !include climates.yaml
lock: !include locks.yaml
var: !include var.yaml
template: !include templates.yaml
cloud:
  alexa:
    filter:
      include_domains:
        - switch
        - button
        - light
        - media_player
        - input_boolean
        - binary_sensor
        - script
homeassistant:
  allowlist_external_dirs:
    - /media
    - /config/nest/event_media
    - /config/www
logbook:
  exclude:
    entities:
      - automation.util_one_second_updater
notify:
  - platform: file
    name: scene_notify_snapshot
    filename: /config/scenes/snapshot.yaml
    timestamp: false
  - name: "hass agent office"
    platform: hass_agent_notifier
    resource: http://192.168.86.50:5115/notify
command_line:
  - sensor:
      unique_id: wan_address
      name: WAN Address
      command: "wget -O - -q https://checkip.amazonaws.com"
      scan_interval: 30
mqtt:
  sensor:
    - name: "Bed Presets"
      state_topic: "homeassistant/bedroom/bed_presets"
      value_template: "{{value_json | length}} Presets"
      json_attributes_topic: "homeassistant/bedroom/bed_presets"
