- platform: template
  sensors:
    washer_door_lock:
      friendly_name: "Washer Door Lock"
      value_template: "{{ state_attr('sensor.front_load_washer','door_lock') }}"

    washer_time_display:
      friendly_name: "Washer Time Display"
      value_template: >
        {% if is_state('sensor.front_load_washer_run_state', '-') %}
        {% elif is_state('sensor.front_load_washer_run_state', 'Standby') %}
          -:--
        {% else %}
          {{ state_attr('sensor.front_load_washer', 'remain_time') }}
        {% endif %}

    dryer_time_display:
      friendly_name: "Dryer Time Display"
      value_template: >
        {% if is_state('sensor.dryer_run_state', '-') %}
        {% elif is_state('sensor.dryer_run_state', 'Standby') %}
          -:--
        {% else %}
          {{ state_attr('sensor.dryer', 'remain_time') }}
        {% endif %}
    dishwasher_time_display:
      friendly_name: "Dish Washer Time Display"
      value_template: >
        {% if is_state('input_boolean.dishwasher_on', 'off') %}
        {% else %}
          {% set f = state_attr('timer.dishwasher_timer', 'finishes_at') %}
          {{ '00:00' if f == None else
          (as_datetime(f) - now()).total_seconds() | timestamp_custom('%H:%M', false) }}
        {% endif %}

    blank:
      friendly_name: "Blank Sensor"
      value_template: ""
