- platform: template
  switches:
    office_ac:
      value_template: "{{ not is_state('climate.gemodulec9cd_window_ac', 'off') }}"
      turn_on:
        service: climate.set_hvac_mode
        data:
          hvac_mode: cool
        target:
          entity_id: climate.gemodulec9cd_window_ac
      turn_off:
        service: climate.set_hvac_mode
        data:
          hvac_mode: "off"
        target:
          entity_id: climate.gemodulec9cd_window_ac
