- platform: template
  switches:
    office_ac:
      value_template: "{{ is_state('climate.gemodulec9cd', 'cool') }}"
      turn_on:
        service: climate.set_hvac_mode
        data:
          hvac_mode: cool
        target:
          device_id: 53dae5dd0352d72d3b507b9707ffe216
      turn_off:
        service: climate.set_hvac_mode
        data:
          hvac_mode: "off"
        target:
          device_id: 53dae5dd0352d72d3b507b9707ffe216
